-- Test schema for H2 database (PostgreSQL compatibility mode)
-- This schema is used for property-based testing

-- Drop tables if they exist
DROP TABLE IF EXISTS wms_owner CASCADE;

-- Owner (货主) table
CREATE TABLE wms_owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    create_date TIMESTAMP,
    create_by VARCHAR(50),
    update_date TIMESTAMP,
    update_by VARCHAR(50),
    delete_flag INTEGER DEFAULT 0,
    version INTEGER DEFAULT 0
);

-- Create index on delete_flag for logical delete queries
CREATE INDEX idx_owner_delete_flag ON wms_owner(delete_flag);
